"""
TL-FPSI synthetic reference simulator (v2, fast).

Implements the ideal counting semantics, SimHash-style band candidate
generation, overflow / no-truncation behavior, and the per-(b,r) metrics
referenced in Section VII of the paper "Threshold-Gated Labeled Fuzzy PSI
with Explicit Leakage for Contamination Audits" (IEEE TDSC submission).

This is NOT a cryptographic implementation. It is a deterministic, seedable
plaintext simulator used to populate Tables XI, XII and Figure 1.

Notation (paper Section VII):
  d = br     fingerprint length in bits
  b         number of bands
  r         rows per band
  tau       Hamming threshold
  K_max     candidate-volume cap (overflow abort)
  n         number of corpus fingerprints
  m         number of benchmark fingerprints
  s         number of injected near matches (s <= m)
  q_star    per-bit agreement of honest-input SimHash model
  t0        global gate threshold

For each (b, r) setting the simulator runs N_TRIALS independent audits.
A near match is generated by sampling a Hamming distance h ~ Binomial(d, 1-q*)
and flipping exactly h bits of a randomly chosen corpus fingerprint; the chosen
benchmark index is the target.
"""

from __future__ import annotations

import json
import os
import statistics
from dataclasses import dataclass
from pathlib import Path

import numpy as np


# -------- Defaults (from paper Section VII-B/C) -----------------------------
N_CORPUS = 800
M_BENCH = 240
S_INJECT = 48
TAU = 8
K_MAX = 12000
N_TRIALS = 100           # 100 trials per setting, matching the placeholder
                         # table description in Section VII-C of the paper.
Q_STAR = 0.9             # target per-bit agreement (SimHash honest-input model);
                         # per the calibration example of paper Section V-D,
                         # q* = 0.9 is the figure used to derive the b >= 49
                         # band threshold under target blocking failure
                         # delta_blk <= 2^{-40}.
SEED_BASE = 20260713

# (b, r, d) settings reported in the paper. d = b * r; (10,10) uses d=100,
# the other three use d=96. The simulator draws the hyperplane matrix of
# shape (d, b*r) and the fingerprint of shape (n, d) per setting.
PARAM_SETTINGS = [
    (8, 12, 96),
    (10, 10, 100),
    (12, 8, 96),
    (16, 6, 96),
]


# -------- Helpers ----------------------------------------------------------
def hamming_le(d: int, fp_a: np.ndarray, fp_b: np.ndarray) -> np.ndarray:
    """Vectorized Hamming distance for two (N, d) uint8 arrays."""
    diff = fp_a.astype(np.int16) - fp_b.astype(np.int16)
    return np.abs(diff).sum(axis=1)


def percentile(xs: list[int], p: float) -> int:
    if not xs:
        return 0
    xs_sorted = sorted(xs)
    k = int(round((p / 100.0) * (len(xs_sorted) - 1)))
    return xs_sorted[k]


# -------- SimHash banding -------------------------------------------------
def make_hyperplanes(rng: np.random.Generator, b: int, r: int, d: int) -> np.ndarray:
    """Return (d, b*r) iid Bernoulli(0.5) hyperplane directions as int8 (-1,+1)."""
    return rng.integers(0, 2, size=(d, b * r), dtype=np.int8) * 2 - 1


def simhash_per_band(fps: np.ndarray, hyperplanes: np.ndarray, b: int, r: int) -> np.ndarray:
    """
    Compute per-band signature bits.

    fps:        (N, d) uint8 {0,1}
    hyperplanes: (d, b*r) int8 {+1,-1}
    returns:    (N, b*r) uint8 {0,1}  where 0/1 indicates sign of inner product
    """
    # Hyperplane vectors have length d, indexed per row; we project onto b*r
    # independent directions. For per-band grouping, we need exactly b*r
    # directions, so the hyperplane matrix must be (d, b*r).
    assert hyperplanes.shape == (fps.shape[1], b * r), (
        f"hyperplanes shape {hyperplanes.shape} != ({fps.shape[1]}, {b*r})"
    )
    # H has columns [+1, -1]; treat fp in {-1, +1} via 2*fp - 1.
    x = fps.astype(np.int8) * 2 - 1                  # (N, d)
    sig = (x @ hyperplanes) > 0                       # (N, b*r)
    return sig.astype(np.uint8)


def pack_band_keys(sig: np.ndarray, b: int, r: int) -> np.ndarray:
    """
    sig: (N, b*r) uint8
    returns: (N, b) uint64 packed band-keys.
    """
    n = sig.shape[0]
    sig = sig.reshape(n, b, r)
    weights = (np.left_shift(np.ones(r, dtype=np.uint64), np.arange(r, dtype=np.uint64)))
    return (sig.astype(np.uint64) * weights).sum(axis=2)


# -------- Trial driver -----------------------------------------------------
def run_trial(rng: np.random.Generator, b: int, r: int, d: int, t0: int) -> dict:
    # 1) draw n + m random fingerprints
    corpus = rng.integers(0, 2, size=(N_CORPUS, d), dtype=np.uint8)
    bench = rng.integers(0, 2, size=(M_BENCH, d), dtype=np.uint8)
    labels = np.array([f"L{j % 4}" for j in range(M_BENCH)], dtype=object)

    # 2) inject s near matches: choose a corpus index i, then a benchmark
    #    index j, and generate a benchmark fingerprint at Hamming distance
    #    h drawn from the honest-input SimHash distribution
    #        p(h | h <= tau) proportional to Bin(d, 1 - q_star)
    #    for h in {0, ..., tau}. This is the conditional form of the
    #    honest-input SimHash model of Assumption simhash: per-bit agreement
    #    is q_star > 0.5, and we condition on the close-pair event
    #    Ham(corpus[i], bench[j]) <= tau. The full-comparison ground truth
    #    is the set of injected pairs whose current Hamming distance is at
    #    most tau at the time the ground truth is computed, not at the
    #    time the pair was first written. If a later inject overwrites the
    #    same benchmark slot j, the previous pair's Hamming distance may
    #    change; the ground truth therefore includes only pairs whose
    #    final Hamming distance is still <= tau. Pairs that are written and
    #    then overwritten are excluded from s_actual as well, since they
    #    are no longer reliable "true" matches under the threshold.
    from math import comb
    weights = np.array([comb(d, h) * (1.0 - Q_STAR) ** h * Q_STAR ** (d - h)
                        for h in range(TAU + 1)], dtype=np.float64)
    weights /= weights.sum()
    inject_pairs: list[tuple[int, int]] = []
    used_bench: set[int] = set()
    used_corpus: set[int] = set()
    tries = 0
    while len(inject_pairs) < S_INJECT and tries < S_INJECT * 200:
        tries += 1
        i = int(rng.integers(0, N_CORPUS))
        if i in used_corpus:
            continue
        j = int(rng.integers(0, M_BENCH))
        if j in used_bench:
            continue
        h = int(rng.choice(TAU + 1, p=weights))
        if h > 0:
            flip = rng.choice(d, size=h, replace=False)
            bench_flip = corpus[i].copy()
            bench_flip[flip] ^= 1
            bench[j] = bench_flip
        inject_pairs.append((i, j))
        used_bench.add(j)
        used_corpus.add(i)
    s_actual = len(inject_pairs)

    # 3) full-comparison ground truth: include only injected pairs whose
    #    final Hamming distance is at most tau. Since each benchmark index
    #    is written exactly once and never overwritten, this is the same
    #    as inject_pairs; we keep the explicit Ham check to make the
    #    invariant self-documenting and to support future per-pair Ham
    #    changes.
    full_mat = np.zeros((M_BENCH, N_CORPUS), dtype=bool)
    for (i, j) in inject_pairs:
        if hamming_le(d, corpus[i][None, :], bench[j][None, :])[0] <= TAU:
            full_mat[j, i] = True
    # 4) blocked candidate generation.
    #
    # The candidate generation rule follows two regimes:
    #   (a) Deterministic-completeness regime (b > tau, Lemma 1 of the paper):
    #       a partition of the d-bit fingerprint into b nonempty disjoint
    #       bands. Two fingerprints agree on a band iff the corresponding
    #       bit slices are bit-identical. Lemma 1 guarantees that every
    #       Hamming-close pair (Ham <= tau) shares at least one exact-match
    #       band, so the candidate relation is exactly the union of the b
    #       disjoint band collisions. No hyperplanes are used.
    #   (b) Probabilistic regime (b <= tau): the standard SimHash banding
    #       of the paper, in which each band's r bits are the result of
    #       projecting the fingerprint onto b*r independent random
    #       hyperplanes. The candidate probability is given by
    #       1 - (1 - q_star^r)^b under Assumption simhash; Lemma 1 does
    #       not apply and some Hamming-close pairs may be missed.
    blocked_mat = np.zeros((M_BENCH, N_CORPUS), dtype=bool)
    if b > TAU:
        # Deterministic raw bit partition: band k = bits [k*r, (k+1)*r).
        # This is the model assumed by Lemma 1.
        for k in range(b):
            lo = k * r
            hi = (k + 1) * r
            c_slice = corpus[:, lo:hi]                   # (n, r)
            b_slice = bench[:, lo:hi]                    # (m, r)
            # Pack bits of each row into a uint64 key
            weights = (np.left_shift(np.ones(r, dtype=np.uint64), np.arange(r, dtype=np.uint64)))
            c_key = (c_slice.astype(np.uint64) * weights).sum(axis=1)
            b_key = (b_slice.astype(np.uint64) * weights).sum(axis=1)
            ck_order = np.argsort(c_key, kind="stable")
            bk_order = np.argsort(b_key, kind="stable")
            ck_sorted = c_key[ck_order]
            bk_sorted = b_key[bk_order]
            ii = 0
            jj = 0
            while ii < N_CORPUS and jj < M_BENCH:
                if ck_sorted[ii] < bk_sorted[jj]:
                    ii += 1
                elif ck_sorted[ii] > bk_sorted[jj]:
                    jj += 1
                else:
                    key = ck_sorted[ii]
                    i_end = ii
                    while i_end < N_CORPUS and ck_sorted[i_end] == key:
                        i_end += 1
                    j_end = jj
                    while j_end < M_BENCH and bk_sorted[j_end] == key:
                        j_end += 1
                    ci = ck_order[ii:i_end]
                    bj = bk_order[jj:j_end]
                    if ci.size and bj.size:
                        II, JJ = np.meshgrid(ci, bj, indexing="ij")
                        blocked_mat[JJ, II] = True
                    ii = i_end
                    jj = j_end
    else:
        # Probabilistic SimHash banding (paper Section IV-A).
        hp = make_hyperplanes(rng, b, r, d)
        c_sig = simhash_per_band(corpus, hp, b, r)
        b_sig = simhash_per_band(bench, hp, b, r)
        ck = pack_band_keys(c_sig, b, r)
        bk = pack_band_keys(b_sig, b, r)
        for k in range(b):
            ck_k = ck[:, k]
            bk_k = bk[:, k]
            ck_order = np.argsort(ck_k, kind="stable")
            bk_order = np.argsort(bk_k, kind="stable")
            ck_sorted = ck_k[ck_order]
            bk_sorted = bk_k[bk_order]
            i = 0
            j = 0
            while i < N_CORPUS and j < M_BENCH:
                if ck_sorted[i] < bk_sorted[j]:
                    i += 1
                elif ck_sorted[i] > bk_sorted[j]:
                    j += 1
                else:
                    key = ck_sorted[i]
                    i_end = i
                    while i_end < N_CORPUS and ck_sorted[i_end] == key:
                        i_end += 1
                    j_end = j
                    while j_end < M_BENCH and bk_sorted[j_end] == key:
                        j_end += 1
                    ci = ck_order[i:i_end]
                    bj = bk_order[j:j_end]
                    if ci.size and bj.size:
                        II, JJ = np.meshgrid(ci, bj, indexing="ij")
                        blocked_mat[JJ, II] = True
                    i = i_end
                    j = j_end

    k_pair = int(blocked_mat.sum())
    overflow = k_pair > K_MAX

    # Lemma 1 invariant: when b > tau and the cap is not exceeded, every
    # Hamming-close pair (Ham(corpus[i], bench[j]) <= tau) must be present
    # in the candidate relation, because at most tau bands can contain a
    # mismatch and b > tau disjoint bands guarantees at least one
    # exact-match band. We count any violation rather than raising, so the
    # simulator reports the failure rate and can be debugged; the count is
    # also exported in the per-trial log.
    det_violations = 0
    if b > TAU and not overflow:
        for (i, j) in inject_pairs:
            if full_mat[j, i] and not blocked_mat[j, i]:
                det_violations += 1

    if overflow:
        blocked_c = 0
        blocked_label: dict[str, int] = {}
        pair_recall = float("nan")
        bench_recall = float("nan")
        global_count_error = 0
        per_label_count_error = 0
        threshold_fn = False
        output_agreement = float("nan")
        full_c = sum(1 for _ in inject_pairs)
        full_label: dict[str, int] = {}
    else:
        if k_pair > 0:
            js, iis = np.where(blocked_mat)
            ham = hamming_le(d, corpus[iis], bench[js])
            keep = ham <= TAU
            js = js[keep]
            iis = iis[keep]
            blocked_mat = np.zeros((M_BENCH, N_CORPUS), dtype=bool)
            blocked_mat[js, iis] = True
        a_j = blocked_mat.any(axis=1)
        blocked_c = int(a_j.sum())
        blocked_label_counts: dict[str, int] = {}
        for j in range(M_BENCH):
            if a_j[j]:
                lbl = labels[j]
                blocked_label_counts[lbl] = blocked_label_counts.get(lbl, 0) + 1
        blocked_label = blocked_label_counts

        a_full = full_mat.any(axis=1)
        full_c = int(a_full.sum())
        full_label_counts: dict[str, int] = {}
        for j in range(M_BENCH):
            if a_full[j]:
                lbl = labels[j]
                full_label_counts[lbl] = full_label_counts.get(lbl, 0) + 1

        n_recovered_pairs = 0
        for (i, j) in inject_pairs:
            if full_mat[j, i] and blocked_mat[j, i]:
                n_recovered_pairs += 1
        n_close_pairs_truth_actual = sum(1 for (i, j) in inject_pairs if full_mat[j, i])
        pair_recall = n_recovered_pairs / max(1, n_close_pairs_truth_actual)

        n_close_bench = {j for (i, j) in inject_pairs if full_mat[j, i]}
        if n_close_bench:
            bench_recall = sum(1 for j in n_close_bench if a_j[j]) / len(n_close_bench)
        else:
            bench_recall = 1.0

        global_count_error = abs(blocked_c - full_c)
        per_label_count_error = max(
            (abs(blocked_label.get(l, 0) - full_label_counts.get(l, 0))
             for l in set(blocked_label) | set(full_label_counts)),
            default=0,
        )
        threshold_fn = (full_c >= t0) and (blocked_c < t0)
        output_agreement = 1.0 if (blocked_c == full_c and blocked_label == full_label_counts) else 0.0

    return {
        "b": b,
        "r": r,
        "d": d,
        "k_pair": k_pair,
        "overflow": overflow,
        "det_violations": det_violations,
        "blocked_c": blocked_c if not overflow else 0,
        "full_c": full_c,
        "output_agreement": output_agreement if not overflow else float("nan"),
        "pair_recall": pair_recall,
        "bench_recall": bench_recall,
        "global_count_error": global_count_error,
        "per_label_count_error": per_label_count_error,
        "threshold_fn": threshold_fn,
        "s_actual": s_actual,
    }


# -------- Main -------------------------------------------------------------
def main(out_dir: str) -> None:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    t0 = max(1, S_INJECT // 4)

    table_xi_rows = []
    table_xii_rows = []
    per_trial_logs = []

    for b, r, d in PARAM_SETTINGS:
        results = []
        for trial in range(N_TRIALS):
            seed = SEED_BASE + 1000 * b + 10 * r + trial
            rng = np.random.default_rng(seed)
            res = run_trial(rng, b, r, d, t0)
            res["trial"] = trial
            res["seed"] = seed
            results.append(res)
            per_trial_logs.append(res)

        ks = [r["k_pair"] for r in results]
        n_overflow = sum(1 for r in results if r["overflow"])
        non_overflow = [r for r in results if not r["overflow"]]
        if non_overflow:
            agreement = sum(r["output_agreement"] for r in non_overflow) / len(non_overflow)
        else:
            agreement = float("nan")
        det_violation_count = sum(r["det_violations"] for r in results)
        table_xi_rows.append({
            "b": b, "r": r, "d": d,
            "overflow_rate": n_overflow / len(results),
            "k_pair_median": percentile(ks, 50),
            "k_pair_p95": percentile(ks, 95),
            "output_agreement": agreement,
            "deterministic_violation_count": det_violation_count,
        })

        if non_overflow:
            table_xii_rows.append({
                "b": b, "r": r,
                "pair_recall": statistics.fmean(r["pair_recall"] for r in non_overflow),
                "bench_item_recall": statistics.fmean(r["bench_recall"] for r in non_overflow),
                "global_count_error_mean": statistics.fmean(r["global_count_error"] for r in non_overflow),
                "per_label_count_error_mean": statistics.fmean(r["per_label_count_error"] for r in non_overflow),
                "threshold_fn_rate": sum(1 for r in non_overflow if r["threshold_fn"]) / len(non_overflow),
                "overflow_rate": n_overflow / len(results),
                "deterministic_violation_count": sum(r["det_violations"] for r in non_overflow),
            })
        else:
            table_xii_rows.append({
                "b": b, "r": r,
                "pair_recall": float("nan"),
                "bench_item_recall": float("nan"),
                "global_count_error_mean": float("nan"),
                "per_label_count_error_mean": float("nan"),
                "threshold_fn_rate": float("nan"),
                "overflow_rate": 1.0,
            })

        print(
            f"(b,r)=({b},{r}): Kpair med={table_xi_rows[-1]['k_pair_median']} "
            f"p95={table_xi_rows[-1]['k_pair_p95']} "
            f"overflow={table_xi_rows[-1]['overflow_rate']:.2f} "
            f"agreement={agreement:.4f} det_viol={det_violation_count} | "
            f"pair_recall={table_xii_rows[-1]['pair_recall']:.4f} "
            f"bench_recall={table_xii_rows[-1]['bench_item_recall']:.4f} "
            f"gerr={table_xii_rows[-1]['global_count_error_mean']:.3f} "
            f"lerr={table_xii_rows[-1]['per_label_count_error_mean']:.3f} "
            f"fn={table_xii_rows[-1]['threshold_fn_rate']:.4f}"
        )

    summary = {
        "schema_version": "tlfpsi-synthetic-eval-v1",
        "config": {
            "n_corpus": N_CORPUS,
            "m_bench": M_BENCH,
            "s_inject": S_INJECT,
            "tau": TAU,
            "K_max": K_MAX,
            "n_trials": N_TRIALS,
            "q_star": Q_STAR,
            "seed_base": SEED_BASE,
            "t0_rule": "max(1, s_inject // 4)",
        },
        "table_xi": table_xi_rows,
        "table_xii": table_xii_rows,
    }
    (out / "summary.json").write_text(json.dumps(summary, indent=2))
    with (out / "per_trial.jsonl").open("w") as f:
        for row in per_trial_logs:
            f.write(json.dumps(row) + "\n")
    print(f"\nWrote {out}/summary.json and {out}/per_trial.jsonl")


if __name__ == "__main__":
    import sys
    out = sys.argv[1] if len(sys.argv) > 1 else "."
    main(out)
